### ISSUE TITLE
`heroku local` command doesn't work

### ISSUE THREAD

**Issue by rice10t** [mpppk/projegrid#9]
`heroku local` コマンドを叩いても`npm release` が失敗し、エラーになってしまう。
今は暫定的に `heroku local:run npm start` で動かしている。

**Comment by mpppk** [comment]
原因
https://github.com/mpppk/projegrid/issues/8#issuecomment-240390518

> 環境変数からfirebase.serviceAccount.privateKeyの値を読み込むときに \n が \n として読み込まれてしまっているから。

とりあえず環境変数から読むのではなく、config.jsに直接値を書き込んでも動くはず

**Comment by mpppk** [comment]
> とりあえず環境変数から読むのではなく、config.jsに直接値を書き込んでも動くはず

動かないっぽい。
#8 とは別の現象のよう。

**Comment by rice10t** [comment]
エラー内容

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Nodist\\v-x64\\6.3.1\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Nodist\\npmv\\3.10.5\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.5
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle projegrid@1.0.0~prestart: projegrid@1.0.0
6 verbose lifecycle projegrid@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle projegrid@1.0.0~prestart: PATH: C:\Program Files (x86)\Nodist\npmv\3.10.5\bin\node-gyp-bin;E:\my\prj\projegrid\node_modules\.bin;C:\Program Files (x86)\Nodist\v-x64\6.3.1;"C:\Program Files (x86)\Heroku\ruby-2.1.7\bin";E:\programming\python\;E:\programming\python\Scripts;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;E:\programming\xampp\php;C:\Program Files\Java\jdk1.8.0_72\bin;E:\programming\curl-7.47.1-win64-mingw\bin;E:\programming\vim74-kaoriya-win64;E:\programming\Vagrant\bin;E:\programming\sbt\bin;C:\Program Files (x86)\Gow\bin;C:\Users\a\.cargo\bin;C:\Program Files\Rust stable GNU 1.7\bin;E:\programming\activator-dist-1.3.9\bin;C:\Users\a\AppData\Roaming\local\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Nodist\bin;C:\Program Files\PostgreSQL\9.5\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\a\AppData\Roaming\local\bin;E:\programming\Ruby22-x64\bin;C:\Ruby22-x64\bin;C:\Users\a\AppData\Local\atom\bin;E:\programming\Docker Toolbox;C:\Program Files (x86)\Microsoft VS Code\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Git\bin
8 verbose lifecycle projegrid@1.0.0~prestart: CWD: E:\my\prj\projegrid
9 silly lifecycle projegrid@1.0.0~prestart: Args: [ '/d /s /c', 'npm run release' ]
10 silly lifecycle projegrid@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle projegrid@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: projegrid@1.0.0 prestart: `npm run release`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\Nodist\npmv\3.10.5\lib\utils\lifecycle.js:242:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\Nodist\npmv\3.10.5\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:852:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
13 verbose pkgid projegrid@1.0.0
14 verbose cwd E:\my\prj\projegrid
15 error Windows_NT 10.0.14393
16 error argv "C:\\Program Files (x86)\\Nodist\\v-x64\\6.3.1\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\3.10.5\\bin\\npm-cli.js" "start"
17 error node v6.3.1
18 error npm  v3.10.5
19 error code ELIFECYCLE
20 error projegrid@1.0.0 prestart: `npm run release`
20 error Exit status 1
21 error Failed at the projegrid@1.0.0 prestart script 'npm run release'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the projegrid package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm run release
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs projegrid
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls projegrid
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

**Comment by rice10t** [comment]
今試してみたら `heroku local:run npm start` もなぜか失敗するようになってました・・・。

```
'webpack' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
```

とのこと。
npm-debug.logの内容は上とまったく同じみたいです。

**Comment by mpppk** [comment]
> 'webpack' は、内部コマンドまたは外部コマンド、
> 操作可能なプログラムまたはバッチ ファイルとして認識されていません。

関係あるかわかりませんが、localではないheroku上で、webpackが見つからない旨のエラーが出ることはありました。
そのときはherokuがデフォルトではdevDependenciesをinstallしないのが原因で、NPM_CONFIG_PRODUCTION=falseという環境変数を追加して解決しました。(これもどうかとは思いますが。。。)
